import { 
  Code2, 
  Hash, 
  Type, 
  FileJson, 
  RefreshCw, 
  ShieldCheck, 
  Binary, 
  Globe, 
  Clock,
  Settings2,
  Lock,
  FileCode,
  FileText,
  Table,
  Fingerprint,
  CaseSensitive,
  AlignLeft,
  Search,
  LayoutGrid,
  Zap,
  Hammer,
  Link,
  Image as ImageIcon,
  Calculator,
  Database,
  Code,
  AlignRight,
  FileSpreadsheet,
  Calendar,
  List,
  QrCode,
  Maximize2,
  Youtube
} from 'lucide-react';

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: any;
  documentation?: string; // Markdown or detailed text
  externalUrl?: string; // Link to official specs/docs
}

export type ToolCategory = 
  | 'Formatters' 
  | 'Encoders/Decoders' 
  | 'Converters' 
  | 'Cryptography' 
  | 'Text Tools' 
  | 'Generators' 
  | 'Networking'
  | 'Time'
  | 'Data Tools'
  | 'Math Tools'
  | 'Image Tools';

export const CATEGORIES: ToolCategory[] = [
  'Formatters',
  'Encoders/Decoders',
  'Converters',
  'Cryptography',
  'Text Tools',
  'Generators',
  'Networking',
  'Time',
  'Data Tools',
  'Math Tools',
  'Image Tools'
];

export const TOOLS: Tool[] = [
  // Formatters
  { id: 'json-prettify', name: 'JSON Prettify', description: 'Indent and format JSON strings', category: 'Formatters', icon: FileJson },
  { id: 'json-minify', name: 'JSON Minify', description: 'Compress JSON strings', category: 'Formatters', icon: FileJson },
  { id: 'json-validate', name: 'JSON Validate', description: 'Verify JSON syntax and catch errors', category: 'Formatters', icon: ShieldCheck },
  { id: 'html-prettify', name: 'HTML Prettify', description: 'Format ugly HTML code', category: 'Formatters', icon: Code2 },
  { id: 'html-minify', name: 'HTML Minify', description: 'Compress HTML into a single line', category: 'Formatters', icon: Code2 },
  { id: 'css-prettify', name: 'CSS Prettify', description: 'Format and indent CSS code', category: 'Formatters', icon: FileCode },
  { id: 'css-minify', name: 'CSS Minify', description: 'Compress CSS styles', category: 'Formatters', icon: FileCode },
  { id: 'js-prettify', name: 'JS Prettify', description: 'Format JavaScript code', category: 'Formatters', icon: FileCode },
  { id: 'js-minify', name: 'JS Minify', description: 'Compress JS code (simple)', category: 'Formatters', icon: FileCode },
  { id: 'js-validate', name: 'JS Validate', description: 'Check JavaScript syntax', category: 'Formatters', icon: ShieldCheck },
  { id: 'xml-prettify', name: 'XML Prettify', description: 'Format XML documents', category: 'Formatters', icon: FileCode },
  { id: 'xml-minify', name: 'XML Minify', description: 'Compress XML strings', category: 'Formatters', icon: FileCode },
  { id: 'sql-prettify', name: 'SQL Formatter', description: 'Prettify and indent SQL queries', category: 'Formatters', icon: Database },
  { id: 'graphql-prettify', name: 'GraphQL Formatter', description: 'Prettify GraphQL queries', category: 'Formatters', icon: Code },
  
  // Encoders/Decoders
  { id: 'base64-encode', name: 'Base64 Encode', description: 'Convert text to Base64', category: 'Encoders/Decoders', icon: Binary },
  { id: 'base64-decode', name: 'Base64 Decode', description: 'Convert Base64 to text', category: 'Encoders/Decoders', icon: Binary },
  { id: 'url-encode', name: 'URL Encode', description: 'Convert special URL characters', category: 'Encoders/Decoders', icon: Globe },
  { id: 'url-decode', name: 'URL Decode', description: 'Decode percent-encoded strings', category: 'Encoders/Decoders', icon: Globe },
  { id: 'url-parse', name: 'URL Parse', description: 'Extract components from a URL', category: 'Encoders/Decoders', icon: Globe },
  { id: 'html-encode', name: 'HTML Escape', description: 'Convert characters to HTML entities', category: 'Encoders/Decoders', icon: Code2 },
  { id: 'html-decode', name: 'HTML Unescape', description: 'Decode HTML entities back to text', category: 'Encoders/Decoders', icon: Code2 },
  { id: 'json-escape', name: 'JSON Escape', description: 'Escape special JSON characters', category: 'Encoders/Decoders', icon: FileJson },
  { id: 'json-unescape', name: 'JSON Unescape', description: 'Unescape JSON strings', category: 'Encoders/Decoders', icon: FileJson },
  { id: 'idn-encode', name: 'IDN Encode', description: 'Unicode domain to Punycode', category: 'Encoders/Decoders', icon: Globe },
  { id: 'idn-decode', name: 'IDN Decode', description: 'Punycode to Unicode domain', category: 'Encoders/Decoders', icon: Globe },
  { id: 'base32-encode', name: 'Base32 Encode', description: 'Convert text to Base32', category: 'Encoders/Decoders', icon: Binary },
  { id: 'base32-decode', name: 'Base32 Decode', description: 'Convert Base32 to text', category: 'Encoders/Decoders', icon: Binary },
  { id: 'base58-encode', name: 'Base58 Encode', description: 'Convert text to Base58', category: 'Encoders/Decoders', icon: Binary },
  { id: 'base58-decode', name: 'Base58 Decode', description: 'Convert Base58 to text', category: 'Encoders/Decoders', icon: Binary },
  { id: 'rot13-decode', name: 'ROT13 Strings', description: 'Shift letters by 13 places', category: 'Encoders/Decoders', icon: RefreshCw },
  { id: 'rot47-decode', name: 'ROT47 Strings', description: 'Shift characters by 47 places', category: 'Encoders/Decoders', icon: RefreshCw },
  { id: 'ascii85-encode', name: 'Ascii85 Encode', description: 'Adobe-style 85-base encoding', category: 'Encoders/Decoders', icon: Binary },
  { id: 'ascii85-decode', name: 'Ascii85 Decode', description: 'Decode Ascii85 strings', category: 'Encoders/Decoders', icon: Binary },
  { id: 'utf8-encode', name: 'UTF8 Encode', description: 'Standard UTF-8 encoding', category: 'Encoders/Decoders', icon: Type },
  { id: 'utf8-decode', name: 'UTF8 Decode', description: 'Decode UTF-8 strings', category: 'Encoders/Decoders', icon: Type },
  { id: 'utf16-encode', name: 'UTF16 Encode', description: 'Standard UTF-16 encoding', category: 'Encoders/Decoders', icon: Type },
  { id: 'utf16-decode', name: 'UTF16 Decode', description: 'Decode UTF-16 strings', category: 'Encoders/Decoders', icon: Type },
  { id: 'uuencode', name: 'Uuencode', description: 'Unix-to-Unix text encoding', category: 'Encoders/Decoders', icon: Binary },
  { id: 'uudecode', name: 'Uudecode', description: 'Decode Uuencoded text', category: 'Encoders/Decoders', icon: Binary },
  { id: 'jwt-decode', name: 'JWT Decoder', description: 'Decode JSON Web Tokens without a secret', category: 'Encoders/Decoders', icon: ShieldCheck },
  
  // Converters
  { id: 'json-to-yaml', name: 'JSON to YAML', description: 'Convert JSON to YAML format', category: 'Converters', icon: RefreshCw },
  { id: 'yaml-to-json', name: 'YAML to JSON', description: 'Convert YAML to JSON format', category: 'Converters', icon: RefreshCw },
  { id: 'csv-to-json', name: 'CSV to JSON', description: 'Convert CSV to JSON structure', category: 'Converters', icon: Table },
  { id: 'json-to-csv', name: 'JSON to CSV', description: 'Convert JSON array to CSV', category: 'Converters', icon: Table },
  { id: 'xml-to-csv', name: 'XML to CSV', description: 'Convert XML data to CSV format', category: 'Converters', icon: Table },
  { id: 'csv-to-xml', name: 'CSV to XML', description: 'Convert CSV data to XML markup', category: 'Converters', icon: Table },
  { id: 'xml-to-json', name: 'XML to JSON', description: 'Convert XML to JSON structure', category: 'Converters', icon: RefreshCw },
  { id: 'json-to-xml', name: 'JSON to XML', description: 'Convert JSON to XML markup', category: 'Converters', icon: RefreshCw },
  { id: 'hex-to-rgb', name: 'Hex to RGB', description: 'Color HEX to Decimal format', category: 'Converters', icon: RefreshCw },
  { id: 'rgb-to-hex', name: 'RGB to Hex', description: 'Color Decimal to HEX format', category: 'Converters', icon: RefreshCw },
  { id: 'cmyk-to-rgb', name: 'CMYK to RGB', description: 'Print color to digital format', category: 'Converters', icon: RefreshCw },
  { id: 'rgb-to-cmyk', name: 'RGB to CMYK', description: 'Digital color to print format', category: 'Converters', icon: RefreshCw },
  { id: 'markdown-to-html', name: 'Markdown to HTML', description: 'Convert MD to HTML markup', category: 'Converters', icon: RefreshCw },
  { id: 'html-to-markdown', name: 'HTML to Markdown', description: 'Convert HTML to MD text', category: 'Converters', icon: RefreshCw },
  { id: 'html-to-jade', name: 'HTML to Jade/Pug', description: 'Convert HTML to Pug templates', category: 'Converters', icon: RefreshCw },
  { id: 'jade-to-html', name: 'Jade/Pug to HTML', description: 'Render Pug templates to HTML', category: 'Converters', icon: RefreshCw },
  { id: 'bbcode-to-html', name: 'BBCode to HTML', description: 'Convert BBCode tags to HTML', category: 'Converters', icon: RefreshCw },
  { id: 'binary-to-octal', name: 'Binary to Octal', description: 'Base-2 to Base-8 conversion', category: 'Converters', icon: Binary },
  { id: 'binary-to-decimal', name: 'Binary to Decimal', description: 'Base-2 to Base-10 conversion', category: 'Converters', icon: Binary },
  { id: 'binary-to-hex', name: 'Binary to Hex', description: 'Base-2 to Base-16 conversion', category: 'Converters', icon: Binary },
  { id: 'octal-to-binary', name: 'Octal to Binary', description: 'Base-8 to Base-2 conversion', category: 'Converters', icon: Binary },
  { id: 'octal-to-decimal', name: 'Octal to Decimal', description: 'Base-8 to Base-10 conversion', category: 'Converters', icon: Binary },
  { id: 'octal-to-hex', name: 'Octal to Hex', description: 'Base-8 to Base-16 conversion', category: 'Converters', icon: Binary },
  { id: 'decimal-to-binary', name: 'Decimal to Binary', description: 'Base-10 to Base-2 conversion', category: 'Converters', icon: Binary },
  { id: 'decimal-to-octal', name: 'Decimal to Octal', description: 'Base-10 to Base-8 conversion', category: 'Converters', icon: Binary },
  { id: 'decimal-to-hex', name: 'Decimal to Hex', description: 'Base-10 to Base-16 conversion', category: 'Converters', icon: Binary },
  { id: 'hex-to-binary', name: 'Hex to Binary', description: 'Base-16 to Base-2 conversion', category: 'Converters', icon: Binary },
  { id: 'hex-to-octal', name: 'Hex to Octal', description: 'Base-16 to Base-8 conversion', category: 'Converters', icon: Binary },
  { id: 'hex-to-decimal', name: 'Hex to Decimal', description: 'Base-16 to Base-10 conversion', category: 'Converters', icon: Binary },
  { id: 'decimal-to-bcd', name: 'Decimal to BCD', description: 'Binary Coded Decimal encoding', category: 'Converters', icon: Binary },
  { id: 'bcd-to-decimal', name: 'BCD to Decimal', description: 'Decode Binary Coded Decimal', category: 'Converters', icon: Binary },
  { id: 'octal-to-bcd', name: 'Octal to BCD', description: 'Convert Octal to BCD', category: 'Converters', icon: Binary },
  { id: 'bcd-to-octal', name: 'BCD to Octal', description: 'Convert BCD to Octal', category: 'Converters', icon: Binary },
  { id: 'hex-to-bcd', name: 'Hex to BCD', description: 'Convert Hexadecimal to BCD', category: 'Converters', icon: Binary },
  { id: 'bcd-to-hex', name: 'BCD to Hex', description: 'Convert BCD to Hexadecimal', category: 'Converters', icon: Binary },
  { id: 'binary-to-gray', name: 'Binary to Gray Code', description: 'Convert Binary to Gray Code', category: 'Converters', icon: Binary },
  { id: 'gray-to-binary', name: 'Gray to Binary', description: 'Convert Gray Code to Binary', category: 'Converters', icon: Binary },
  { id: 'octal-to-gray', name: 'Octal to Gray Code', description: 'Convert Octal to Gray Code', category: 'Converters', icon: Binary },
  { id: 'gray-to-octal', name: 'Gray to Octal', description: 'Convert Gray Code to Octal', category: 'Converters', icon: Binary },
  { id: 'decimal-to-gray', name: 'Decimal to Gray Code', description: 'Convert Decimal to Gray Code', category: 'Converters', icon: Binary },
  { id: 'gray-to-decimal', name: 'Gray to Decimal', description: 'Convert Gray Code to Decimal', category: 'Converters', icon: Binary },
  { id: 'hex-to-gray', name: 'Hex to Gray Code', description: 'Convert Hex to Gray Code', category: 'Converters', icon: Binary },
  { id: 'gray-to-hex', name: 'Gray to Hex', description: 'Convert Gray Code to Hex', category: 'Converters', icon: Binary },
  { id: 'base-converter', name: 'Any Base Converter', description: 'Convert numbers between any base (2-36)', category: 'Converters', icon: RefreshCw },
  { id: 'number-to-words', name: 'Numbers to Words', description: 'Convert digits to spoken text', category: 'Converters', icon: Type },
  { id: 'words-to-number', name: 'Words to Numbers', description: 'Convert spoken numbers to digits', category: 'Converters', icon: Type },
  { id: 'miles-to-km', name: 'Miles to Kilometers', description: 'Convert distance (mi to km)', category: 'Converters', icon: RefreshCw },
  { id: 'km-to-miles', name: 'Kilometers to Miles', description: 'Convert distance (km to mi)', category: 'Converters', icon: RefreshCw },
  { id: 'celsius-to-fahrenheit', name: 'Celsius to Fahrenheit', description: 'Temperature conversion (\u00B0C to \u00B0F)', category: 'Converters', icon: RefreshCw },
  { id: 'fahrenheit-to-celsius', name: 'Fahrenheit to Celsius', description: 'Temperature conversion (\u00B0F to \u00B0C)', category: 'Converters', icon: RefreshCw },
  { id: 'degrees-to-radians', name: 'Degrees to Radians', description: 'Angle conversion (deg to rad)', category: 'Converters', icon: RefreshCw },
  { id: 'radians-to-degrees', name: 'Radians to Degrees', description: 'Angle conversion (rad to deg)', category: 'Converters', icon: RefreshCw },
  { id: 'pounds-to-kilograms', name: 'Pounds to Kilograms', description: 'Weight conversion (lb to kg)', category: 'Converters', icon: RefreshCw },
  { id: 'kilograms-to-pounds', name: 'Kilograms to Pounds', description: 'Weight conversion (kg to lb)', category: 'Converters', icon: RefreshCw },
  { id: 'hex-to-hsl', name: 'Hex to HSL', description: 'Convert color Hex to HSL', category: 'Converters', icon: RefreshCw },
  { id: 'hsl-to-hex', name: 'HSL to Hex', description: 'Convert color HSL to Hex', category: 'Converters', icon: RefreshCw },
  { id: 'toml-to-json', name: 'TOML to JSON', description: 'Convert TOML to JSON format', category: 'Converters', icon: RefreshCw },
  { id: 'json-to-toml', name: 'JSON to TOML', description: 'Convert JSON to TOML format', category: 'Converters', icon: RefreshCw },
  { id: 'cron-to-text', name: 'Cron to Human', description: 'Translate cron expressions to English', category: 'Converters', icon: Clock },
  { id: 'roman-to-decimal', name: 'Roman to Decimal', description: 'Convert Roman numerals to Arabic', category: 'Converters', icon: Calculator },
  { id: 'decimal-to-roman', name: 'Decimal to Roman', description: 'Convert Arabic numbers to Roman', category: 'Converters', icon: Calculator },
  { id: 'scientific-to-decimal', name: 'Scientific to Decimal', description: 'Convert 1e3 to 1000', category: 'Converters', icon: Calculator },
  { id: 'decimal-to-scientific', name: 'Decimal to Scientific', description: 'Convert 1000 to 1e3', category: 'Converters', icon: Calculator },
  
  // Cryptography
  { id: 'hash-generator', name: 'Hash Generator', description: 'MD5, SHA-1, SHA-256 calculator', category: 'Cryptography', icon: ShieldCheck },
  { id: 'multi-hash', name: 'All Hashes at Once!', description: 'Compute all hash types simultaneously', category: 'Cryptography', icon: ShieldCheck },
  { id: 'bcrypt-generator', name: 'Bcrypt Password', description: 'Create or verify bcrypt hashes', category: 'Cryptography', icon: Lock },
  { id: 'scrypt-generator', name: 'Scrypt Password', description: 'Create or verify scrypt hashes', category: 'Cryptography', icon: Lock },
  { id: 'mysql-password', name: 'MySQL Password', description: 'MySQL 5.x+ hash format', category: 'Cryptography', icon: Database },
  { id: 'mariadb-password', name: 'MariaDB Password', description: 'MariaDB compatible password hash', category: 'Cryptography', icon: Database },
  { id: 'postgresql-password', name: 'PostgreSQL Password', description: 'PostgreSQL MD5 hash format', category: 'Cryptography', icon: Database },
  { id: 'md2-hash', name: 'MD2 Hash', description: 'Message Digest 2 (Legacy)', category: 'Cryptography', icon: ShieldCheck },
  { id: 'md4-hash', name: 'MD4 Hash', description: 'Message Digest 4 (Legacy)', category: 'Cryptography', icon: ShieldCheck },
  { id: 'md5-hash', name: 'MD5 Hash', description: 'Message Digest 5', category: 'Cryptography', icon: ShieldCheck },
  { id: 'md6-hash', name: 'MD6 Hash', description: 'Message Digest 6 (Experimental)', category: 'Cryptography', icon: ShieldCheck },
  { id: 'ripemd128-hash', name: 'RipeMD-128 Hash', description: '128-bit RipeMD algorithm', category: 'Cryptography', icon: ShieldCheck },
  { id: 'ripemd160-hash', name: 'RipeMD-160 Hash', description: '160-bit RipeMD algorithm', category: 'Cryptography', icon: ShieldCheck },
  { id: 'ripemd256-hash', name: 'RipeMD-256 Hash', description: '256-bit RipeMD algorithm', category: 'Cryptography', icon: ShieldCheck },
  { id: 'ripemd320-hash', name: 'RipeMD-320 Hash', description: '320-bit RipeMD algorithm', category: 'Cryptography', icon: ShieldCheck },
  { id: 'sha1-hash', name: 'SHA-1 Hash', description: 'Secure Hash Algorithm 1', category: 'Cryptography', icon: ShieldCheck },
  { id: 'sha224-hash', name: 'SHA-224 Hash', description: 'SHA-2 Variant (224-bit)', category: 'Cryptography', icon: ShieldCheck },
  { id: 'sha256-hash', name: 'SHA-256 Hash', description: 'SHA-2 Variant (256-bit)', category: 'Cryptography', icon: ShieldCheck },
  { id: 'sha384-hash', name: 'SHA-384 Hash', description: 'SHA-2 Variant (384-bit)', category: 'Cryptography', icon: ShieldCheck },
  { id: 'sha512-hash', name: 'SHA-512 Hash', description: 'SHA-2 Variant (512-bit)', category: 'Cryptography', icon: ShieldCheck },
  { id: 'sha3-hash', name: 'SHA-3 Hash', description: 'Keccak-based SHA-3', category: 'Cryptography', icon: ShieldCheck },
  { id: 'crc16-hash', name: 'CRC16 Hash', description: '16-bit redundancy check', category: 'Cryptography', icon: ShieldCheck },
  { id: 'crc32-hash', name: 'CRC32 Hash', description: '32-bit redundancy check', category: 'Cryptography', icon: ShieldCheck },
  { id: 'adler32-hash', name: 'Adler32 Hash', description: 'Checksum algorithm', category: 'Cryptography', icon: ShieldCheck },
  { id: 'whirlpool-hash', name: 'Whirlpool Hash', description: 'Whirlpool hash algorithm', category: 'Cryptography', icon: ShieldCheck },
  { id: 'ntlm-hash', name: 'NTLM Hash', description: 'Windows NTLM hash', category: 'Cryptography', icon: ShieldCheck },
  { id: 'aes-encrypt', name: 'AES Encryption', description: 'Advanced Encryption Standard', category: 'Cryptography', icon: Lock },
  { id: 'des-encrypt', name: 'DES Encryption', description: 'Data Encryption Standard', category: 'Cryptography', icon: Lock },
  { id: 'triple-des-encrypt', name: 'TripleDES Encryption', description: '3DES secure algorithm', category: 'Cryptography', icon: Lock },
  { id: 'rc4-encrypt', name: 'RC4 Encryption', description: 'Stream cipher algorithm', category: 'Cryptography', icon: Lock },
  { id: 'rabbit-encrypt', name: 'Rabbit Encryption', description: 'High-speed stream cipher', category: 'Cryptography', icon: Lock },
  { id: 'xor-encrypt', name: 'XOR Encryption', description: 'Simple bitwise encryption', category: 'Cryptography', icon: Lock },
  { id: 'hmac-generator', name: 'HMAC Generator', description: 'Keyed-hash message authentication', category: 'Cryptography', icon: Fingerprint },
  
  // Text Tools
  { id: 'text-transform', name: 'Case Converter', description: 'Upper, lower, title case', category: 'Text Tools', icon: CaseSensitive },
  { id: 'lowercase-text', name: 'Lowercase Text', description: 'Convert all text to lowercase', category: 'Text Tools', icon: Type },
  { id: 'uppercase-text', name: 'Uppercase Text', description: 'Convert all text to uppercase', category: 'Text Tools', icon: Type },
  { id: 'randomcase-text', name: 'Randomcase Text', description: 'Randomly capitalize letters', category: 'Text Tools', icon: Type },
  { id: 'titlecase-text', name: 'Titlecase Text', description: 'Capitalize first letter of each word', category: 'Text Tools', icon: Type },
  { id: 'invertcase-text', name: 'Invert Text Case', description: 'Swap upper and lower case', category: 'Text Tools', icon: CaseSensitive },
  { id: 'repeat-text', name: 'Repeat Text', description: 'Repeat string multiple times', category: 'Text Tools', icon: RefreshCw },
  { id: 'replace-text', name: 'Replace Text', description: 'Search and replace string content', category: 'Text Tools', icon: Search },
  { id: 'reverse-text', name: 'Reverse Text', description: 'Flip text content backwards', category: 'Text Tools', icon: RefreshCw },
  { id: 'reverse-lines-text', name: 'Reverse Text Lines', description: 'Flip the order of lines', category: 'Text Tools', icon: RefreshCw },
  { id: 'truncate-text', name: 'Truncate Text', description: 'Shorten text to specific length', category: 'Text Tools', icon: Hammer },
  { id: 'trim-text', name: 'Trim Text', description: 'Remove leading/trailing whitespace', category: 'Text Tools', icon: AlignLeft },
  { id: 'remove-duplicates', name: 'Remove Duplicates', description: 'Clean up list items', category: 'Text Tools', icon: AlignLeft },
  { id: 'text-stats', name: 'Text Stats', description: 'Word, char, line count', category: 'Text Tools', icon: AlignLeft },
  { id: 'find-longest-line', name: 'Find Longest Text Line', description: 'Identify the longest line', category: 'Text Tools', icon: Search },
  { id: 'find-shortest-line', name: 'Find Shortest Text Line', description: 'Identify the shortest line', category: 'Text Tools', icon: Search },
  { id: 'sort-text', name: 'Sort Text', description: 'Alphabetical or numerical sort', category: 'Text Tools', icon: AlignLeft },
  { id: 'sort-words', name: 'Sort Words', description: 'Sort words within text', category: 'Text Tools', icon: AlignLeft },
  { id: 'sort-text-length', name: 'Sort Text by Length', description: 'Shortest to longest or vice versa', category: 'Text Tools', icon: AlignLeft },
  { id: 'sort-ip-addresses', name: 'Sort IP Addresses', description: 'Proper numerical IP sorting', category: 'Text Tools', icon: Globe },
  { id: 'word-wrap', name: 'Word Wrap', description: 'Wrap text at specific width', category: 'Text Tools', icon: AlignLeft },
  { id: 'number-lines', name: 'Number Text Lines', description: 'Prepend line numbers to text', category: 'Text Tools', icon: AlignLeft },
  { id: 'letter-frequency', name: 'Find Letter Frequency', description: 'Count occurrences of each letter', category: 'Text Tools', icon: AlignLeft },
  { id: 'word-frequency', name: 'Find Word Frequency', description: 'Count occurrences of each word', category: 'Text Tools', icon: AlignLeft },
  { id: 'extract-emails', name: 'Extract All Emails', description: 'Pull all emails from text', category: 'Text Tools', icon: Search },
  { id: 'extract-urls', name: 'Extract All URLs', description: 'Pull all web addresses from text', category: 'Text Tools', icon: Search },
  { id: 'extract-numbers', name: 'Extract All Numbers', description: 'Pull all digits/numbers from text', category: 'Text Tools', icon: Search },
  { id: 'morse-encode', name: 'Morse Encode', description: 'Convert text to Morse code', category: 'Text Tools', icon: Binary },
  { id: 'morse-decode', name: 'Morse Decode', description: 'Convert Morse to readable text', category: 'Text Tools', icon: Binary },
  { id: 'strip-html', name: 'Strip HTML Tags', description: 'Remove all markup from text', category: 'Text Tools', icon: AlignLeft },
  { id: 'html-extract-text', name: 'Extract HTML Text', description: 'Deep extract text content', category: 'Text Tools', icon: AlignLeft },
  { id: 'bbcode-extract-text', name: 'Extract BBCode Text', description: 'Remove forum tags', category: 'Text Tools', icon: AlignLeft },
  { id: 'json-extract-text', name: 'Extract JSON Text', description: 'Extract all string values', category: 'Text Tools', icon: AlignLeft },
  { id: 'text-to-html-entities', name: 'Text to HTML Entities', description: 'Strict encode all chars', category: 'Text Tools', icon: AlignLeft },
  { id: 'text-to-binary', name: 'Text to Binary', description: 'Convert string to bit stream', category: 'Text Tools', icon: Binary },
  { id: 'binary-to-text', name: 'Binary to Text', description: 'Convert bits back to characters', category: 'Text Tools', icon: Binary },
  { id: 'text-to-hex', name: 'Text to Hex', description: 'Convert text to hexadecimal', category: 'Text Tools', icon: Binary },
  { id: 'hex-to-text', name: 'Hex to Text', description: 'Convert hexadecimal to text', category: 'Text Tools', icon: Binary },
  { id: 'text-to-octal', name: 'Text to Octal', description: 'Convert text to octal values', category: 'Text Tools', icon: Binary },
  { id: 'octal-to-text', name: 'Octal to Text', description: 'Convert octal back to text', category: 'Text Tools', icon: Binary },
  { id: 'text-to-decimal', name: 'Text to Decimal', description: 'Convert text to decimal numbers', category: 'Text Tools', icon: Binary },
  { id: 'decimal-to-text', name: 'Decimal to Text', description: 'Convert decimal back to text', category: 'Text Tools', icon: Binary },
  { id: 'rotate-text', name: 'Rotate Text', description: 'Circular shift text content', category: 'Text Tools', icon: RefreshCw },
  { id: 'center-text', name: 'Center Text', description: 'Center align text with padding', category: 'Text Tools', icon: AlignLeft },
  { id: 'right-align-text', name: 'Right-Align Text', description: 'Right justify text with padding', category: 'Text Tools', icon: AlignLeft },
  { id: 'justify-text', name: 'Justify Text', description: 'Evenly distribute words', category: 'Text Tools', icon: AlignLeft },
  { id: 'prefix-suffix-lines', name: 'Prefix/Suffix Lines', description: 'Add text to start/end of lines', category: 'Text Tools', icon: AlignLeft },
  { id: 'delete-empty-lines', name: 'Delete Empty Lines', description: 'Remove all blank lines', category: 'Text Tools', icon: AlignLeft },
  { id: 'shuffle-lines', name: 'Shuffle Text Lines', description: 'Randomize the order of lines', category: 'Text Tools', icon: RefreshCw },
  { id: 'join-lines', name: 'Join Text Lines', description: 'Merge multiple lines into one', category: 'Text Tools', icon: AlignLeft },
  { id: 'split-strings', name: 'Split Strings', description: 'Divide text by separator', category: 'Text Tools', icon: AlignLeft },
  { id: 'remove-accents', name: 'Remove Accents', description: 'Normalize accented characters', category: 'Text Tools', icon: Type },
  { id: 'remove-punctuation', name: 'Remove Punctuation', description: 'Extract plain text only', category: 'Text Tools', icon: AlignLeft },
  { id: 'thousands-separator', name: 'Add Thousand Separators', description: 'Format numbers with commas', category: 'Text Tools', icon: Calculator },
  { id: 'list-merge', name: 'Merge Lists', description: 'Combine two or more text lists', category: 'Text Tools', icon: AlignLeft },
  { id: 'list-zip', name: 'Zip Text Lists', description: 'Interleave items from two lists', category: 'Text Tools', icon: AlignLeft },
  { id: 'list-intersect', name: 'Intersect Text Lists', description: 'Find common items in two lists', category: 'Text Tools', icon: AlignLeft },
  { id: 'list-diff', name: 'Difference of Text Lists', description: 'Find items unique to first list', category: 'Text Tools', icon: AlignLeft },
  { id: 'grep-text', name: 'Grep Text', description: 'Filter lines matching pattern', category: 'Text Tools', icon: Search },
  { id: 'head-text', name: 'Head Text', description: 'Show the first few lines', category: 'Text Tools', icon: AlignLeft },
  { id: 'tail-text', name: 'Tail Text', description: 'Show the last few lines', category: 'Text Tools', icon: AlignLeft },
  { id: 'line-range', name: 'Extract Line Range', description: 'Select specific lines from text', category: 'Text Tools', icon: AlignLeft },
  { id: 'add-backslashes', name: 'Add Backslashes', description: 'Escape special characters', category: 'Text Tools', icon: Hammer },
  { id: 'strip-backslashes', name: 'Strip Backslashes', description: 'Unescape text content', category: 'Text Tools', icon: Hammer },
  { id: 'sort-numbers', name: 'Sort Numbers', description: 'Proper numerical sequence sort', category: 'Text Tools', icon: Calculator },
  { id: 'split-words', name: 'Split into Words', description: 'Convert text to word list', category: 'Text Tools', icon: AlignLeft },
  { id: 'phrase-frequency', name: 'Find Phrase Frequency', description: 'Count occurrences of N-word phrases', category: 'Text Tools', icon: AlignLeft },
  { id: 'regexp-extract', name: 'Extract Regexp Matches', description: 'Pull text matching pattern', category: 'Text Tools', icon: Search },
  { id: 'regexp-replace', name: 'Replace Regexp Matches', description: 'Advanced search and replace', category: 'Text Tools', icon: Search },
  { id: 'text-length', name: 'Find Text Length', description: 'Total character count display', category: 'Text Tools', icon: Type },
  { id: 'spaces-to-tabs', name: 'Convert Spaces to Tabs', description: 'Change indentation to tabs', category: 'Text Tools', icon: AlignLeft },
  { id: 'tabs-to-spaces', name: 'Convert Tabs to Spaces', description: 'Change indentation to spaces', category: 'Text Tools', icon: AlignLeft },
  { id: 'spaces-to-newlines', name: 'Convert Spaces to Newlines', description: 'Change spaces to line breaks', category: 'Text Tools', icon: AlignLeft },
  { id: 'newlines-to-spaces', name: 'Convert Newlines to Spaces', description: 'Join lines with spaces', category: 'Text Tools', icon: AlignLeft },
  { id: 'remove-duplicate-spaces', name: 'Remove Duplicate Spaces', description: 'Collapse multiple spaces into one', category: 'Text Tools', icon: AlignLeft },
  { id: 'remove-all-whitespaces', name: 'Remove All Whitespaces', description: 'Strip all space/tab/newline', category: 'Text Tools', icon: AlignLeft },
  { id: 'printf-tool', name: 'Printf/Sprintf Text', description: 'Format strings using templates', category: 'Text Tools', icon: Code },
  { id: 'left-pad', name: 'Left-Pad Text', description: 'Add padding to start of lines', category: 'Text Tools', icon: AlignLeft },
  { id: 'right-pad', name: 'Right-Pad Text', description: 'Add padding to end of lines', category: 'Text Tools', icon: AlignRight },
  { id: 'capitalize-words', name: 'Capitalize Words', description: 'Uppercase first letter of every word', category: 'Text Tools', icon: Type },
  { id: 'format-columns', name: 'Format Text Columns', description: 'Align text into tabular columns', category: 'Text Tools', icon: FileSpreadsheet },
  { id: 'char-count', name: 'Find Number of Letters', description: 'Clean letter character count', category: 'Text Tools', icon: Type },
  { id: 'text-to-slug', name: 'Text to Slug', description: 'Create URL friendly strings', category: 'Text Tools', icon: Link },
  { id: 'escape-html', name: 'Escape HTML', description: 'Prevent XSS by escaping HTML', category: 'Text Tools', icon: Code },
  { id: 'word-count', name: 'Find Number of Words', description: 'Total word count display', category: 'Text Tools', icon: Type },
  { id: 'line-count', name: 'Find Number of Lines', description: 'Total line count display', category: 'Text Tools', icon: Type },
  { id: 'paragraph-count', name: 'Find Number of Paragraphs', description: 'Total paragraph count display', category: 'Text Tools', icon: Type },
  
  // Generators
  { id: 'uuid-generator', name: 'Random UUID Generator', description: 'Generate random UUID v4', category: 'Generators', icon: Fingerprint },
  { id: 'guid-generator', name: 'Random GUID Generator', description: 'Generate global unique identifiers', category: 'Generators', icon: Fingerprint },
  { id: 'password-generator', name: 'Random Password Generator', description: 'Secure random passwords', category: 'Generators', icon: ShieldCheck },
  { id: 'string-generator', name: 'Random String Generator', description: 'Generate alpha-numeric strings', category: 'Generators', icon: Type },
  { id: 'number-generator', name: 'Random Number Generator', description: 'Generate integers within range', category: 'Generators', icon: Calculator },
  { id: 'decimal-generator', name: 'Random Decimal Fraction', description: 'Generate floating point numbers', category: 'Generators', icon: Calculator },
  { id: 'binary-generator', name: 'Random Binary Generator', description: 'Generate strings of 0s and 1s', category: 'Generators', icon: Binary },
  { id: 'octal-generator', name: 'Random Octal Generator', description: 'Generate base-8 numbers', category: 'Generators', icon: Binary },
  { id: 'hex-generator', name: 'Random Hex Generator', description: 'Generate hexadecimal strings', category: 'Generators', icon: Binary },
  { id: 'byte-generator', name: 'Random Byte Generator', description: 'Generate raw byte sequences', category: 'Generators', icon: Binary },
  { id: 'ip-generator', name: 'Random IP Generator', description: 'Generate random IPv4 addresses', category: 'Generators', icon: Globe },
  { id: 'mac-generator', name: 'Random MAC Generator', description: 'Generate random hardware addresses', category: 'Generators', icon: Globe },
  { id: 'date-generator', name: 'Random Date Generator', description: 'Generate dates in specific range', category: 'Generators', icon: Calendar },
  { id: 'time-generator', name: 'Random Time Generator', description: 'Generate 24h or 12h time strings', category: 'Generators', icon: Clock },
  { id: 'json-generator', name: 'Random JSON Generator', description: 'Generate structured mock JSON', category: 'Generators', icon: Code },
  { id: 'xml-generator', name: 'Random XML Generator', description: 'Generate mock XML documents', category: 'Generators', icon: Code },
  { id: 'yaml-generator', name: 'Random YAML Generator', description: 'Generate mock YAML data', category: 'Generators', icon: Code },
  { id: 'csv-generator', name: 'Random CSV Generator', description: 'Generate comma-separated values', category: 'Generators', icon: FileSpreadsheet },
  { id: 'tsv-generator', name: 'Random TSV Generator', description: 'Generate tab-separated values', category: 'Generators', icon: FileSpreadsheet },
  { id: 'regex-generator', name: 'Random Text from RegEx', description: 'Generate strings that match a pattern', category: 'Generators', icon: Search },
  { id: 'shuffle-letters', name: 'Shuffle Letters', description: 'Randomize character order in words', category: 'Generators', icon: RefreshCw },
  { id: 'pick-random', name: 'Pick a Random Item', description: 'Select random lines from text', category: 'Generators', icon: List },
  { id: 'prime-generator', name: 'Prime Number Generator', description: 'Generate a sequence of prime numbers', category: 'Generators', icon: Calculator },
  { id: 'fibonacci-generator', name: 'Fibonacci Generator', description: 'Generate Fibonacci sequence terms', category: 'Generators', icon: Calculator },
  { id: 'pi-generator', name: 'Pi Digit Generator', description: 'Show digits of Pi (\u03C0)', category: 'Generators', icon: Calculator },
  { id: 'euler-generator', name: 'Euler Digit Generator', description: 'Show digits of Euler\'s number (e)', category: 'Generators', icon: Calculator },
  { id: 'qr-generator', name: 'QR Code Generator', description: 'Create customizable QR codes', category: 'Generators', icon: QrCode },
  { id: 'lorem-ipsum', name: 'Lorem Ipsum Gen', description: 'Generate placeholder text for design', category: 'Generators', icon: Type },
  { id: 'youtube-link-generator', name: 'YouTube Link Gen', description: 'Convert Video IDs to all YouTube link formats', category: 'Generators', icon: Youtube },
  
  // Networking
  { id: 'ip-lookup', name: 'What\'s my IP?', description: 'Detect and display IP info', category: 'Networking', icon: Globe },
  { id: 'ip-to-binary', name: 'IP to Binary', description: 'Convert IP to 32-bit sequence', category: 'Networking', icon: Binary },
  { id: 'binary-to-ip', name: 'Binary to IP', description: 'Convert 32-bit sequence to IP', category: 'Networking', icon: Binary },
  { id: 'ip-to-decimal', name: 'IP to Decimal', description: 'Convert IP to integer format', category: 'Networking', icon: Globe },
  { id: 'decimal-to-ip', name: 'Decimal to IP', description: 'Convert integer back to IP', category: 'Networking', icon: Globe },
  { id: 'subnet-calculator', name: 'Subnet Calculator', description: 'Calculate network ranges and masks', category: 'Networking', icon: Globe },
  { id: 'browser-info', name: 'Browser Info', description: 'Display user agent and browser details', category: 'Networking', icon: Globe },
  
  // Time
  { id: 'unix-time', name: 'Unix Time', description: 'Format and convert timestamps', category: 'Time', icon: Clock },
  { id: 'unix-to-utc', name: 'Unix to UTC', description: 'Convert Unix timestamp to UTC date', category: 'Time', icon: Clock },
  { id: 'utc-to-unix', name: 'UTC to Unix', description: 'Convert UTC date to Unix timestamp', category: 'Time', icon: Clock },
  { id: 'seconds-to-hms', name: 'Seconds to H:M:S', description: 'Format seconds into H:M:S string', category: 'Time', icon: Clock },
  { id: 'hms-to-seconds', name: 'H:M:S to Seconds', description: 'Convert H:M:S duration to seconds', category: 'Time', icon: Clock },
  { id: 'seconds-to-human', name: 'Seconds to Human Time', description: 'Format seconds as readable duration', category: 'Time', icon: Clock },
  { id: 'time-diff', name: 'Time Difference', description: 'Calculate duration between two dates', category: 'Time', icon: Clock },
  { id: 'world-clock', name: 'World Clock', description: 'Current time in multiple timezones', category: 'Time', icon: Globe },
  { id: 'leap-year-check', name: 'Leap Year Checker', description: 'Check if a year is a leap year', category: 'Time', icon: Calendar },
  { id: 'week-number', name: 'Week Number Finder', description: 'Find ISO week number for a date', category: 'Time', icon: Calendar },
  { id: 'countdown-timer', name: 'Countdown Timer', description: 'Set a timer with notification', category: 'Time', icon: Clock },
  { id: 'stopwatch-gen', name: 'Stopwatch', description: 'Measure time intervals', category: 'Time', icon: Clock },
  
  // Data Tools
  { id: 'transpose-csv', name: 'Transpose CSV', description: 'Swap CSV rows and columns', category: 'Data Tools', icon: Table },
  { id: 'csv-delimiter', name: 'Change CSV Delimiter', description: 'Convert CSV to different separators', category: 'Data Tools', icon: Table },
  { id: 'csv-to-tsv', name: 'CSV to TSV', description: 'Convert CSV to Tab-Separated Values', category: 'Data Tools', icon: Table },
  { id: 'tsv-to-csv', name: 'TSV to CSV', description: 'Convert TSV to Comma-Separated Values', category: 'Data Tools', icon: Table },
  
  // Math Tools
  { id: 'binary-sum', name: 'Binary Sum', description: 'Add two binary numbers', category: 'Math Tools', icon: Binary },
  { id: 'binary-product', name: 'Binary Product', description: 'Multiply two binary numbers', category: 'Math Tools', icon: Binary },
  { id: 'binary-and', name: 'Binary Bitwise AND', description: 'Logical AND of binary strings', category: 'Math Tools', icon: Settings2 },
  { id: 'binary-nand', name: 'Binary Bitwise NAND', description: 'Logical NAND of binary strings', category: 'Math Tools', icon: Settings2 },
  { id: 'binary-or', name: 'Binary Bitwise OR', description: 'Logical OR of binary strings', category: 'Math Tools', icon: Settings2 },
  { id: 'binary-nor', name: 'Binary Bitwise NOR', description: 'Logical NOR of binary strings', category: 'Math Tools', icon: Settings2 },
  { id: 'binary-xor', name: 'Binary Bitwise XOR', description: 'Logical XOR of binary strings', category: 'Math Tools', icon: Settings2 },
  { id: 'binary-xnor', name: 'Binary Bitwise XNOR', description: 'Logical XNOR of binary strings', category: 'Math Tools', icon: Settings2 },
  { id: 'binary-not', name: 'Binary Bitwise NOT', description: 'Logical NOT of a binary string', category: 'Math Tools', icon: Settings2 },
  { id: 'binary-invert', name: 'Invert Binary String', description: 'Flip all 0s and 1s', category: 'Math Tools', icon: RefreshCw },
  { id: 'binary-reverse', name: 'Reverse Binary String', description: 'Reverse order of bits', category: 'Math Tools', icon: RefreshCw },
  { id: 'binary-shift', name: 'Shift Binary Number', description: 'Circular shift binary bits', category: 'Math Tools', icon: RefreshCw },
  { id: 'binary-rotate-left', name: 'Rotate Binary Left', description: 'Rotate bits to the left', category: 'Math Tools', icon: RefreshCw },
  { id: 'binary-rotate-right', name: 'Rotate Binary Right', description: 'Rotate bits to the right', category: 'Math Tools', icon: RefreshCw },
  { id: 'round-up', name: 'Round Numbers Up', description: 'Ceiling function for numbers', category: 'Math Tools', icon: Calculator },
  { id: 'round-down', name: 'Round Numbers Down', description: 'Floor function for numbers', category: 'Math Tools', icon: Calculator },
  { id: 'aspect-ratio', name: 'Aspect Ratio Calc', description: 'Calculate screen and image ratios', category: 'Math Tools', icon: Maximize2 },
  
  // Image Tools
  { id: 'image-to-base64', name: 'Convert Image to Base64', description: 'Get Data URI string for images', category: 'Image Tools', icon: Binary },
  { id: 'image-converter', name: 'Image Format Converter', description: 'Convert between PNG, JPG, WEBP', category: 'Image Tools', icon: ImageIcon },
  { id: 'jpg-to-png', name: 'Convert JPG to PNG', description: 'Transform JPEG images to PNG format', category: 'Image Tools', icon: ImageIcon },
  { id: 'png-to-jpg', name: 'Convert PNG to JPG', description: 'Transform PNG images to JPEG format', category: 'Image Tools', icon: ImageIcon },
  { id: 'gif-to-png', name: 'Convert GIF to PNG', description: 'Transform GIF to PNG format', category: 'Image Tools', icon: ImageIcon },
  { id: 'gif-to-jpg', name: 'Convert GIF to JPG', description: 'Transform GIF to JPEG format', category: 'Image Tools', icon: ImageIcon },
  { id: 'bmp-to-png', name: 'Convert BMP to PNG', description: 'Transform BMP to PNG format', category: 'Image Tools', icon: ImageIcon },
  { id: 'bmp-to-jpg', name: 'Convert BMP to JPG', description: 'Transform BMP to JPEG format', category: 'Image Tools', icon: ImageIcon },
  { id: 'image-resize', name: 'Resize Image', description: 'Change image dimensions', category: 'Image Tools', icon: Hammer },
  { id: 'image-crop', name: 'Crop Image', description: 'Select and cut image regions', category: 'Image Tools', icon: Hammer },
];
